In [35]:
import numpy as np

In [36]:
def init_weights(k):
    x = np.zeros((k, k))
    return x

def set_weights(M, neurons, memory):
    memory.append(neurons)
    for i in range(0, len(M)):
        for j in range(0, len(M)):
            if i == j:
                M[i][j] = 0
            else:
                M[i][j] = M[i][j] + neurons[i]*neurons[j]
            

def activity_rule(M, neurons):
    for i in range(0, len(M)):
        for j in range(0, len(M)):
            a = np.sum(M[i][j]*neurons[j])
        if a >= 0:
            neurons[i] = 1
        else:
            neurons[i] = -1
            

In [37]:
mem = []

In [38]:
w = init_weights(4)
print(w)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [39]:
v1 = np.array([1, -1, -1, 1])

In [40]:
set_weights(w, v1, mem)
print(w)

[[ 0. -1. -1.  1.]
 [-1.  0.  1. -1.]
 [-1.  1.  0. -1.]
 [ 1. -1. -1.  0.]]


In [45]:
def recall(V_c, M):
    V_out = np.zeros(len(M))
    for i in range(0, len(M)):
        c = 0
        for j in range(0, len(M)):
            if i != j:
                c += M[i][j]*V_c[j]
        if c >= 0:
            V_out[i] = 1
        else:
            V_out[i] = -1
    return V_out

In [46]:
corrupted_mem = np.array([1, 1, -1, 1])

recall(corrupted_mem, w)

array([ 1., -1., -1.,  1.])

In [47]:
corrupted_mem_2 = np.array([1, -1, -1, -1])

recall(corrupted_mem_2, w)

array([ 1., -1., -1.,  1.])

In [44]:
def capacity_measurer():
    for i in range

4